name: CD

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Tag repository
        id: tag
        run: echo "::set-output name=date::$(date +'%s')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push flaskapp
        uses: docker/build-push-action@v4
        env: 
            TAG: ${{ steps.date.outputs.tag }}
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:$TAG

      - name: Build and push postgres
        uses: docker/build-push-action@v4
        env: 
            TAG: ${{ steps.date.outputs.tag }}
        with:
            context: .
            file: ./postgres/Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgres:$TAG