name: CD (Continuous Delivery)

on:
  push:
    branches: [ "main" ]

jobs:

  build-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      

      - name: Tag repository
        id: date
        run: echo "::set-output name=date::$(date +'%s')"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push flaskapp
        uses: docker/build-push-action@v4
        env:
            USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            TAG: ${{ steps.date.outputs.date }}
        with:
            context: ./app
            file: ./app/Dockerfile
            push: true
            tags: $USERNAME/flaskapp:$TAG
          
      - name: Build and push postgres
        uses: docker/build-push-action@v4
        env:
            USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            TAG: ${{ steps.date.outputs.date }}
        with:
            context: ./postgres
            file: ./postgres/Dockerfile
            push: true
            tags: $USERNAME/postgres:$TAG

          
